/* vim:ts=4:sw=4:expandtab
 * (No tabs, indent level is 4 spaces)  */
/*****************************************************************************
 * File:            fm_errno.h
 * Creation Date:   September 16, 2005
 * Last updated:    March 27, 2015
 * Description:     Constants and string table for error messages and return
 *                  constants. 
 *
 *                  THIS FILE IS AUTO-GENERATED BY THE BUILD SYSTEM, DO
 *                  NOT MODIFY THIS FILE.  MODIFY common/ERRORS INSTEAD.
 *                  MD5 HASH OF SOURCE IS 851be0a91c4657482b52a514b913ae01.
 *
 *                  Use "make error-tables" to autogenerate this file.
 *
 * Copyright (c) 2005 - 2015, Intel Corporation
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Intel Corporation nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *****************************************************************************/

#include "fm_std.h"

#ifndef __FM_FM_ERRNO_H
#define __FM_FM_ERRNO_H

/** A status word returned by Fulcrum API functions to
 *  indicate the success or failure of the function call. */
typedef fm_int fm_status;

/**************************************************/
/** Fulcrum error codes
 *  \ingroup constStatus
 *  \page statusCodes
 *
 *  These constants are the status code values
 *  returned by most API services as type fm_status.
 **************************************************/
/** \ingroup constStatus
 * @{ */

/** OK. */
#define FM_OK                                     0

/** Unspecified failure. */
#define FM_FAIL                                   1

/** Invalid argument. */
#define FM_ERR_INVALID_ARGUMENT                   2

/** Feature is unsupported. */
#define FM_ERR_UNSUPPORTED                        3

/** Unable to allocate memory. */
#define FM_ERR_NO_MEM                             4

/** Specified key was not found. */
#define FM_ERR_NOT_FOUND                          5

/** Specified key already exists. */
#define FM_ERR_ALREADY_EXISTS                     6

/** Reached end of iteration. */
#define FM_ERR_NO_MORE                            7

/** A data structure was modified while iterating over it. */
#define FM_ERR_MODIFIED_WHILE_ITERATING           8

/** A necessary initialization function has not been called first. */
#define FM_ERR_UNINITIALIZED                      9

/** A program assertion check failed. */
#define FM_ERR_ASSERTION_FAILED                   10

/** Invalid switch number. */
#define FM_ERR_INVALID_SWITCH                     11

/** Invalid VLAN ID. */
#define FM_ERR_INVALID_VLAN                       12

/** Buffer was too small to fit data. */
#define FM_ERR_BUFFER_FULL                        13

/** MA table bank was full. */
#define FM_ERR_ADDR_BANK_FULL                     14

/** Address was not found in MA Table. */
#define FM_ERR_ADDR_NOT_FOUND                     15

/** Attribute does not exist or is unsupported. */
#define FM_ERR_INVALID_ATTRIB                     16

/** Port is already a member of a LAG. */
#define FM_ERR_ALREADYUSED_PORT                   17

/** No room for additional ports in this LAG. */
#define FM_ERR_FULL_LAG                           18

/** Invalid LAG identifier. */
#define FM_ERR_INVALID_LAG                        19

/** Invalid port number. */
#define FM_ERR_INVALID_PORT                       20

/** Reached maximum LAG count. */
#define FM_ERR_NO_FREE_LAG                        21

/** Invalid port state. */
#define FM_ERR_INVALID_PORT_STATE                 22

/** Invalid submode. */
#define FM_ERR_INVALID_SUBMODE                    23

/** Pending list is full. */
#define FM_ERR_PENDING_LIST_FULL                  24

/** Invalid mirror. */
#define FM_ERR_INVALID_MIRROR                     25

/** Invalid destination port mask specified. */
#define FM_ERR_INVALID_DSTMASK                    26

/** Invalid source port mask. */
#define FM_ERR_INVALID_SRCMASK                    27

/** Invalid MAC address. */
#define FM_ERR_INVALID_MACADDR                    28

/** Invalid priority. */
#define FM_ERR_INVALID_PRIORITY                   29

/** Invalid address match. */
#define FM_ERR_INVALID_ADDR_MATCH                 30

/** Invalid trigger number. */
#define FM_ERR_INVALID_TRIG                       31

/** Invalid MAC Address Table entry type. */
#define FM_ERR_INVALID_ENTRYTYPE                  32

/** No free trigger slots remaining. */
#define FM_ERR_NO_FREE_TRIG                       33

/** No free trigger resources remaining. */
#define FM_ERR_NO_FREE_TRIG_RES                   34

/** No VLAN counter resource available/allocated. */
#define FM_ERR_NO_VLANCOUNTER                     35

/** Current chip configuration is invalid. */
#define FM_ERR_BAD_SWITCH_CONFIG                  36

/** Unable to lock frame handler PLL. */
#define FM_ERR_NO_PLL_LOCK                        37

/** Switch's Boot FSM did not finish properly. */
#define FM_ERR_NO_BOOT                            38

/** Port mirror group is invalid or already in use. */
#define FM_ERR_INVALID_PORT_MIRROR_GROUP          39

/** No (more) ports left in the port mirror group. */
#define FM_ERR_NO_PORTS_IN_MIRROR_GROUP           40

/** ACL is invalid or already in use. */
#define FM_ERR_INVALID_ACL                        41

/** ACL rule is invalid or already in use. */
#define FM_ERR_INVALID_ACL_RULE                   42

/** ACL subsystem has not been enabled with ''FM_QOS_ACL_ENABLE'' for FM2000 devices or api.FM4000.boot.ffuEnable for FM3000 and FM4000 devices. */
#define FM_ERR_ACL_DISABLED                       43

/** No (more) rules left in ACL. */
#define FM_ERR_NO_RULES_IN_ACL                    44

/** No (more) matching ACLs found. */
#define FM_ERR_NO_ACLS                            45

/** No more trigger hardware resources are available (FM2000 only). */
#define FM_ERR_ACL_TABLE_FULL                     46

/** Insufficient hardware resources to support the compiled ACL configuration. See ''FM_FFU_SLICE_ALLOCATIONS''. */
#define FM_ERR_ACLS_TOO_BIG                       47

/** No (more) link aggregation groups in system. */
#define FM_ERR_NO_LAGS                            48

/** No (more) ports in link aggregation group. */
#define FM_ERR_NO_PORTS_IN_LAG                    49

/** No (more) switches. */
#define FM_ERR_NO_SWITCHES                        50

/** An IP protocol version was indicated for an ACL that is not available on the device being configured. */
#define FM_ERR_INVALID_ACL_IP_VERSION             51

/** An ACL precedence value is out of range. */
#define FM_ERR_INVALID_ACL_PRECEDENCE             52

/** The parameter specified for a particular ACL rule option is not valid for that option. */
#define FM_ERR_INVALID_ACL_PARAM                  53

/** Policer does not exist or cannot be created. */
#define FM_ERR_INVALID_POLICER                    54

/** A policer DSCP down map entry is out of range. */
#define FM_ERR_INVALID_DSCP_MAP                   55

/** A policer switch priority down map entry is out of range. */
#define FM_ERR_INVALID_SWPRI_MAP                  56

/** An invalid ACL binary image was specified. */
#define FM_ERR_INVALID_ACL_IMAGE                  57

/** The ACL compiler (''fmCompileACL'') was unable to produce a valid ACL binary image from the current ACL configuration, likely due to an invalid configuration (for example specifying an unknown mapper value). */
#define FM_ERR_ACL_COMPILE                        58

/** The compiled ACL binary image will not fit into the space provided by the caller. */
#define FM_ERR_ACL_IMAGE_OVERFLOW                 59

/** An unsupported switch type has been provided. */
#define FM_ERR_INVALID_SWITCH_TYPE                60

/** A parity error was encountered when reading a register. */
#define FM_ERR_PARITY                             61

/** A register contained an illegal or uninterpretable value. */
#define FM_ERR_INVALID_REGISTER_CONTENTS          62

/** Invalid FFU slice specification. */
#define FM_ERR_INVALID_SLICE                      63

/** The slot argument to an FFU mapper function is out of range. */
#define FM_ERR_INVALID_SLOT                       64

/** An attempt was made to add a duplicate link to a switch aggregate. */
#define FM_ERR_SWAG_DUPLICATE_LINK                65

/** A switch aggregate switch's trunk list is full - no more links may be added to the trunk. */
#define FM_ERR_SWAG_TRUNK_LIST_FULL               66

/** A switch aggregate switch has no more trunks available. */
#define FM_ERR_SWAG_NO_MORE_TRUNKS                67

/** A block of logical port destination table entries cannot be allocated. */
#define FM_ERR_LPORT_DESTS_UNAVAILABLE            68

/** A logical port CAM/RAM entry cannot be allocated. */
#define FM_ERR_LPORT_CAM_UNAVAILABLE              69

/** No symbol lock on SERDES (required for BIST). */
#define FM_ERR_NO_SYMBOL_LOCK                     70

/** The vlan already exists and thus cannot be created. */
#define FM_ERR_VLAN_ALREADY_EXISTS                71

/** The specified switch is not up. */
#define FM_ERR_SWITCH_NOT_UP                      72

/** Attempt to operate on an invalid buffer pointer. */
#define FM_ERR_BAD_BUFFER                         73

/** Frame is too large for sending over the CPU interface. */
#define FM_ERR_FRAME_TOO_LARGE                    74

/** The specified VLAN counter group ID does not reference a valid VLAN counter group. */
#define FM_ERR_INVALID_VCID                       75

/** No available unallocated logical ports. */
#define FM_ERR_LOG_PORT_UNAVAILABLE               76

/** This FFU resource is already owned by another component. */
#define FM_ERR_FFU_RES_OWNED                      77

/** No FFU resources are available. */
#define FM_ERR_NO_FFU_RES_FOUND                   78

/** This property is not valid given the current pause mode. */
#define FM_ERR_INVALID_PAUSE_MODE                 79

/** Key was not found in the attribute database. */
#define FM_ERR_KEY_NOT_FOUND                      80

/** Invalid value argument supplied to API function. */
#define FM_ERR_INVALID_VALUE                      81

/** The ARP table is full. */
#define FM_ERR_ARP_TABLE_FULL                     82

/** Duplicate ARP entry. */
#define FM_ERR_DUPLICATE_ARP_ENTRY                83

/** Table is full. */
#define FM_ERR_TABLE_FULL                         84

/** Invalid IP interface. */
#define FM_ERR_INVALID_INTERFACE                  85

/** Invalid multicast group. */
#define FM_ERR_INVALID_MULTICAST_GROUP            86

/** Invalid Virtual Router ID. */
#define FM_ERR_INVALID_VRID                       87

/** Too many routes in ECMP Group. */
#define FM_ERR_ECMP_GROUP_FULL                    88

/** Multicast Group is active. */
#define FM_ERR_MCAST_GROUP_ACTIVE                 89

/** Multicast Group already attached to an address. */
#define FM_ERR_MCAST_GROUP_ALREADY_ASSIGNED       90

/** Too many virtual routers in use. */
#define FM_ERR_TOO_MANY_VIRTUAL_ROUTERS           91

/** Vlan already assigned to an interface. */
#define FM_ERR_VLAN_ALREADY_ASSIGNED              92

/** No trigger is available. */
#define FM_ERR_TRIGGER_UNAVAILABLE                93

/** No rate limiter is available. */
#define FM_ERR_RATELIMITER_UNAVAILABLE            94

/** Invalid storm controller. */
#define FM_ERR_INVALID_STORM_CTRL                 95

/** No storm controller found. */
#define FM_ERR_NO_STORM_CONTROLLERS               96

/** No storm controller condition found. */
#define FM_ERR_NO_STORM_CONDITION                 97

/** No storm controller action found. */
#define FM_ERR_NO_STORM_ACTION                    98

/** Invalid storm controller condition. */
#define FM_ERR_INVALID_STORM_COND                 99

/** Attempt to set an attribute that is under API control when ''FM_AUTO_PAUSE_MODE'' is enabled. */
#define FM_ERR_INVALID_QOS_MODE                   100

/** No policers found. */
#define FM_ERR_NO_POLICERS                        101

/** Exceeding the maximum number of conditions for a storm controller. */
#define FM_ERR_STORM_COND_EXCEEDED                102

/** Exceeding the maximum number of actions for a storm controller. */
#define FM_ERR_STORM_ACTION_EXCEEDED              103

/** Invalid storm controller action. */
#define FM_ERR_INVALID_ACTION                     104

/** Unrecognized register name. */
#define FM_ERR_UNKNOWN_REGISTER                   105

/** Register snapshot memory is full. */
#define FM_ERR_REG_SNAPSHOT_FULL                  106

/** A Multicast Address has not been assigned to a multicast group. */
#define FM_ERR_MCAST_ADDR_NOT_ASSIGNED            107

/** Multicast Group is not active. */
#define FM_ERR_MCAST_GROUP_NOT_ACTIVE             108

/** Invalid spanning tree mode. */
#define FM_ERR_INVALID_STP_MODE                   109

/** There are no mirror groups existing. */
#define FM_ERR_NO_MIRROR_GROUPS_EXIST             110

/** The specified port is already added to another mirror group. */
#define FM_ERR_PORT_ALREADY_MIRRORED              111

/** No more storm controllers can be created. */
#define FM_ERR_NO_FREE_STORM_CTRL                 112

/** Multicast Address already assigned to a multicast group. */
#define FM_ERR_MCAST_ADDRESS_IN_USE               113

/** Use Multicast Group functions to configure multicast addresses. */
#define FM_ERR_USE_MCAST_FUNCTIONS                114

/** There are not enough multicast resources to perform this operation. */
#define FM_ERR_NO_MCAST_RESOURCES                 115

/** Not a Multicast Address. */
#define FM_ERR_NOT_MULTICAST_ADDRESS              116

/** Virtual Router ID is already in use. */
#define FM_ERR_VRID_ALREADY_IN_USE                117

/** Physical Router may not be deleted. */
#define FM_ERR_PHYS_ROUTER_NOT_DELETABLE          118

/** Port is a member of a Link Aggregation Group. */
#define FM_ERR_PORT_IS_IN_LAG                     119

/** Egress ACLs require the highest-numbered slice be allocated. */
#define FM_ERR_EGRESS_ACLS_REQUIRE_LAST_MINSLICE  120

/** Switch Aggregate is not empty. */
#define FM_ERR_SWITCH_AGGREGATE_NOT_EMPTY         121

/** Invalid Switch Aggregate (SWAG) Identifier. */
#define FM_ERR_INVALID_SWITCH_AGGREGATE           122

/** Switch is already a switch aggregate member. */
#define FM_ERR_SWITCH_ALREADY_IN_AGGREGATE        123

/** Switch is not down. */
#define FM_ERR_SWITCH_IS_NOT_DOWN                 124

/** Switch is not in a switch aggregate. */
#define FM_ERR_SWITCH_NOT_IN_AGGREGATE            125

/** Can't return the range for an FFU resource, because it is not contiguous. */
#define FM_ERR_NON_CONTIGUOUS_RESOURCE            126

/** Counter/policer bank number out of range. */
#define FM_ERR_INVALID_COUNTER_BANK               127

/** Counter/policer index number out of range. */
#define FM_ERR_INVALID_COUNTER_INDEX              128

/** This operation is invalid for the current mode of this LBG. */
#define FM_ERR_INVALID_LBG_STATE                  129

/** Invalid number of ports in the LBG. */
#define FM_ERR_INVALID_LBG_PORT_COUNT             130

/** The total usage for all members does not sum to 100%. */
#define FM_ERR_INVALID_LBG_DISTRIB                131

/** The LBG member port is in an unknown state. */
#define FM_ERR_INVALID_LBG_PORT_STATE             132

/** The LBG member port does not have a valid redirect target. */
#define FM_ERR_INVALID_LBG_PORT_REDIRECT          133

/** This LBG has no standby ports to redirect to. */
#define FM_ERR_NO_LBG_STANDBY_PORTS               134

/** Request only valid with a physical switch. */
#define FM_ERR_PHYSICAL_SWITCH_ONLY               135

/** Not enough free resources exist to complete this operation. */
#define FM_ERR_NO_FREE_RESOURCES                  136

/** Invalid sFlow instance ID. */
#define FM_ERR_INVALID_SFLOW_INSTANCE             137

/** Invalid sFlow attribute. */
#define FM_ERR_INVALID_SFLOW_ATTR                 138

/** No sFlow port found. */
#define FM_ERR_NO_SFLOW_PORT                      139

/** No trigger Id found. */
#define FM_ERR_NO_TRIGGER_ID                      140

/** FIBM operation timeout. */
#define FM_ERR_FIBM_TIMEOUT                       141

/** FIBM is not enabled. */
#define FM_ERR_FIBM_NOT_ENABLED                   142

/** Invalid FIBM response. */
#define FM_ERR_FIBM_INVALID_RESPONSE              143

/** Glort range too small to address all logical ports. */
#define FM_ERR_GLORT_RANGE_TOO_SMALL              144

/** There are no (more) forwarding rules. */
#define FM_ERR_NO_FORWARDING_RULES                145

/** Port is not a member of the load balancing group. */
#define FM_ERR_PORT_NOT_LBG_MEMBER                146

/** Invalid load balancing group. */
#define FM_ERR_INVALID_LBG                        147

/** Transmit packet queue is full. */
#define FM_ERR_TX_PACKET_QUEUE_FULL               148

/** Port is in use. */
#define FM_ERR_PORT_IN_USE                        149

/** There are not enough LAG resources to perform this operation. */
#define FM_ERR_NO_LAG_RESOURCES                   150

/** There are not enough LBG resources to perform this operation. */
#define FM_ERR_NO_LBG_RESOURCES                   151

/** LAG is already in use. */
#define FM_ERR_LAG_IN_USE                         152

/** No priority mapper resources are available to be allocated. */
#define FM_ERR_NO_FREE_PRIORITY_MAPPER            153

/** Invalid priority mapper ID. */
#define FM_ERR_INVALID_PRIORITY_MAPPER            154

/** Invalid priority map. */
#define FM_ERR_INVALID_PRIORITY_MAP               155

/** No switch priority assigned to priority mapper. */
#define FM_ERR_SWPRI_UNASSIGNED                   156

/** Operation cannot be performed on the specified register. */
#define FM_ERR_INVALID_REGISTER                   157

/** The specified glort is already in use. */
#define FM_ERR_GLORT_IN_USE                       158

/** The switch aggregate is not up. */
#define FM_ERR_SWAG_NOT_UP                        159

/** No glorts have been allocated using an fmAllocateStack* function. */
#define FM_ERR_NO_GLORTS_ALLOCATED                160

/** No more CVLAN mappings can be created. */
#define FM_ERR_CVLAN_MAPPING_FULL                 161

/** Mapper is full. */
#define FM_ERR_MAPPER_FULL                        162

/** Invalid IP address mask. */
#define FM_ERR_INVALID_ADDR_MASK                  163

/** No active ports in load balancing group. */
#define FM_ERR_NO_ACTIVE_PORTS_IN_LBG             164

/** No more port sets can be created. */
#define FM_ERR_NO_FREE_PORT_SET                   165

/** Specified port set is not valid. */
#define FM_ERR_INVALID_PORT_SET                   166

/** There are no (more) port sets. */
#define FM_ERR_NO_PORT_SET                        167

/** There are no (more) port set ports. */
#define FM_ERR_NO_PORT_SET_PORT                   168

/** Internal portsets cannot be modified. */
#define FM_ERR_PORTSET_IS_INTERNAL                169

/** The new egress scheduler configuration is invalid and cannot be applied. */
#define FM_ERR_INVALID_NEW_ESCHED_CONFIG          170

/** The active egress scheduler configuration has an error. */
#define FM_ERR_INVALID_ACTIVE_ESCHED_CONFIG       171

/** Static MA Table entry already exists. */
#define FM_ERR_STATIC_ADDR_EXISTS                 172

/** Index is out of range. */
#define FM_ERR_INVALID_INDEX                      173

/** (Not used.) */
#define FM_ERR_SPARE1                             174

/** Invalid FID number. */
#define FM_ERR_INVALID_FID                        175

/** Invalid port MAC number. */
#define FM_ERR_INVALID_PORT_MAC                   176

/** Invalid port lane number. */
#define FM_ERR_INVALID_PORT_LANE                  177

/** Invalid Ethernet interface mode. */
#define FM_ERR_INVALID_ETH_MODE                   178

/** Per-Lag attribute cannot be set on a member port. */
#define FM_ERR_PER_LAG_ATTRIBUTE                  179

/** Per-port attribute cannot be set on a lag logical port. */
#define FM_ERR_NOT_PER_LAG_ATTRIBUTE              180

/** The ECMP Group is in use. */
#define FM_ERR_ECMP_GROUP_IN_USE                  181

/** The ECMP Group is full. */
#define FM_ERR_ECMP_GROUP_IS_FULL                 182

/** Mixing Narrow and Wide Next Hops in an ECMP group is not supported. */
#define FM_ERR_MIXING_NARROW_AND_WIDE_NEXTHOPS    183

/** FFU slice redistribution insufficient for existing Unicast routes. */
#define FM_ERR_INSUFFICIENT_UNICAST_ROUTE_SPACE   184

/** FFU slice redistribution insufficient for existing Multicast routes. */
#define FM_ERR_INSUFFICIENT_MULTICAST_ROUTE_SPACE 185

/** FFU slice redistribution insufficient for existing ACLs. */
#define FM_ERR_INSUFFICIENT_ACL_SPACE             186

/** FFU slice redistribution insufficient for existing CVLANs. */
#define FM_ERR_INSUFFICIENT_CVLAN_SPACE           187

/** Unable to perform the requested operation without stopping traffic. */
#define FM_ERR_TRAFFIC_STOP_REQUIRED              188

/** No VLAN reserved for Per-VLAN spanning tree mode. */
#define FM_ERR_NEED_RESERVED_VLAN                 189

/** There are no (more) ACL rule ingress ports. */
#define FM_ERR_NO_ACL_RULE_INGRESS_PORT           190

/** Invalid scenario key parameters. */
#define FM_ERR_INVALID_SCENARIO                   191

/** Invalid key multiplexer selection. */
#define FM_ERR_INVALID_MUX_SELECT                 192

/** Invalid FFU remap point profile configuration. */
#define FM_ERR_INVALID_REMAP_CFG                  193

/** Invalid L3 hash profile. */
#define FM_ERR_INVALID_HASH_CFG                   194

/** Invalid FFU Rule. */
#define FM_ERR_INVALID_RULE                       195

/** Requested operation requires a logical port. */
#define FM_ERR_LOG_PORT_REQUIRED                  196

/** Invalid Mapper ID specified. */
#define FM_ERR_INVALID_MAPPER                     197

/** API call invalid in current state. */
#define FM_ERR_INVALID_STATE                      198

/** Invalid CRM identifier. */
#define FM_ERR_INVALID_CRM                        199

/** No CRM indexes are available. */
#define FM_ERR_CRM_UNAVAILABLE                    200

/** Invalid Multicast Group State for this Operation. */
#define FM_ERR_MCAST_INVALID_STATE                201

/** Invalid LBG mode. */
#define FM_ERR_INVALID_LBG_MODE                   202

/** Invalid LBG port mode transition. */
#define FM_ERR_INVALID_LBG_PORT_TRANS             203

/** Tunnel is in use. */
#define FM_ERR_TUNNEL_IN_USE                      204

/** There are no routes that serve the specified IP address. */
#define FM_ERR_NO_ROUTE_TO_HOST                   205

/** Required lock not taken. */
#define FM_ERR_LOCK_NOT_TAKEN                     206

/** Unable to initialize lock. */
#define FM_ERR_LOCK_INIT                          207

/** Unable to destroy lock. */
#define FM_ERR_LOCK_DESTROY                       208

/** Unable to capture lock. */
#define FM_ERR_UNABLE_TO_LOCK                     209

/** Unable to release lock. */
#define FM_ERR_UNABLE_TO_UNLOCK                   210

/** Unable to get the current system time. */
#define FM_ERR_BAD_GETTIME                        211

/** No events available at this time. */
#define FM_ERR_NO_EVENTS_AVAILABLE                212

/** Error in removing event from queue. */
#define FM_ERR_REMOVING_EVENT                     213

/** Unable to send an event to a thread because its event queue is full. */
#define FM_ERR_EVENT_QUEUE_FULL                   214

/** Thread creation failed. */
#define FM_ERR_UNABLE_TO_CREATE_THREAD            215

/** Condition variable creation failed. */
#define FM_ERR_UNABLE_TO_CREATE_COND              216

/** Unable to send signal to condition variable. */
#define FM_ERR_UNABLE_TO_SIGNAL_COND              217

/** Wait on condition failed. */
#define FM_ERR_CONDWAIT_FAILED                    218

/** Event queue is empty. */
#define FM_ERR_EVENT_QUEUE_EMPTY                  219

/** Heap is full. */
#define FM_ERR_HEAP_FULL                          220

/** The specified lock has not been initialized. */
#define FM_ERR_LOCK_UNINITIALIZED                 221

/** A timeout occurred while trying to capture a semaphore. */
#define FM_ERR_SEM_TIMEOUT                        222

/** A timeout occurred while trying to capture a lock. */
#define FM_ERR_LOCK_TIMEOUT                       223

/** A lock was captured or released out of order with respect to other locks. */
#define FM_ERR_LOCK_PRECEDENCE                    224

/** Unable to open info device node. */
#define FM_ERR_OPENING_INFO_DEVICE_NODE           225

/** Unable to open device node. */
#define FM_ERR_OPENING_DEVICE_NODE                226

/** A device ioctl call failed. */
#define FM_ERR_BAD_IOCTL                          227

/** The switch could not be identified. */
#define FM_ERR_CANT_IDENTIFY_SWITCH               228

/** MDIO access error. */
#define FM_ERR_MDIO_NO_RESPONSE                   229

/** I2C access error */
#define FM_ERR_I2C_NO_RESPONSE                    230

/** The total number of active and failover LBG ports exceeded the maximum allowed by LAG pruning (16 for FM4000). */
#define FM_ERR_TOO_MANY_PORTS_FOR_LBG_REDIRECT    231

/** No (more) vlans left in the mirror group. */
#define FM_ERR_NO_VLANS_IN_MIRROR_GROUP           232

/** Port is internal. */
#define FM_ERR_PORT_IS_INTERNAL                   233

/** Current DFE mode is not static. */
#define FM_ERR_DFE_NOT_STATIC                     234

/** Desired DFE mode not compatible with interface. */
#define FM_ERR_INCOMPATIBLE_DFE                   235

/** Invalid trap code specified. */
#define FM_ERR_INVALID_TRAP_CODE                  236

/** FFU resource is already in use. */
#define FM_ERR_FFU_RESOURCE_IN_USE                237

/** The microcode image file is missing. */
#define FM_ERR_MICROCODE_IMAGE_FILE_MISSING       238

/** The microcode image file has errors and is invalid. */
#define FM_ERR_MICROCODE_IMAGE_INVALID            239

/** Scheduler token not found or invalid. */
#define FM_ERR_INVALID_SCHED_TOKEN                240

/** Unable to initialize scheduler. */
#define FM_ERR_SCHED_INIT                         241

/** The operation could not complete because it would oversubscribe the scheduler.  */
#define FM_ERR_SCHED_OVERSUBSCRIBED               242

/** A scheduler rule violation was detected, or no scheduler solution was found.  */
#define FM_ERR_SCHED_VIOLATION                    243

/** No more tunnel IDs can be created. */
#define FM_ERR_NO_FREE_TUNNEL_ID                  244

/** The EEPROM version used is not compatible with this API version. */
#define FM_ERR_EEPROM_VERSION_MISMATCH            245

/** No (more) eye diagram samples left. */
#define FM_ERR_NO_EYE_DIAGRAM_SAMPLES             246

/** Timeout waiting for DFE to complete (BIST). */
#define FM_ERR_DFE_TIMEOUT                        247

/** The specified GPIO signal ID is invalid. */
#define FM_ERR_INVALID_GPIO_ID                    248

/** The specified GPIO signal bank is invalid. */
#define FM_ERR_INVALID_GPIO_BANK                  249

/** The specified operation is invalid in the current GPIO signal state. */
#define FM_ERR_INVALID_GPIO_STATE                 250

/** GPIO access error. */
#define FM_ERR_GPIO_NO_RESPONSE                   251

/** The specified resource is internal and can only be modified by API internals. */
#define FM_ERR_INTERNAL_RESOURCE                  252

/** The specified state machine handle does not correspond to an instantiated state machine. */
#define FM_ERR_STATE_MACHINE_HANDLE               253

/** There was a state machine type mismatch or the type is being used or it's unregistered. */
#define FM_ERR_STATE_MACHINE_TYPE                 254

/** An attempt was made to bind a new State Transition Table to a state machine that is already bound. */
#define FM_ERR_BOUND_STATE_MACHINE                255

/** Invalid mailbox transaction ID. */
#define FM_ERR_INVALID_TRANSACTION_ID             256

/** Policer parameters conflict with the existing policer bank configuration. */
#define FM_ERR_CONFLICT_POLICER_PARAM             257

/** The specified tunnel type parameter is invalid or not supported. */
#define FM_ERR_TUNNEL_TYPE                        258

/** The specified tunnel rule bin is full. */
#define FM_ERR_TUNNEL_BIN_FULL                    259

/** The specified tunnel rule has conflicting conditions or actions. */
#define FM_ERR_TUNNEL_CONFLICT                    260

/** The specified tunnel rule encap flow does not exist. */
#define FM_ERR_TUNNEL_NO_ENCAP_FLOW               261

/** No more tunnel group can be created on this engine. */
#define FM_ERR_TUNNEL_NO_FREE_GROUP               262

/** No more tunnel lookup entries available on this engine. */
#define FM_ERR_TUNNEL_LOOKUP_FULL                 263

/** No more tunnel glort entries available on this engine. */
#define FM_ERR_TUNNEL_GLORT_FULL                  264

/** No more tunnel counter entries available on this engine. */
#define FM_ERR_TUNNEL_COUNT_FULL                  265

/** No more tunnel flow entries available on this engine. */
#define FM_ERR_TUNNEL_FLOW_FULL                   266

/** No more tunnel flow entries available on this group. */
#define FM_ERR_TUNNEL_GROUP_FULL                  267

/** The specified rule or encap flow does not define count action. */
#define FM_ERR_TUNNEL_NO_COUNT                    268

/** The specified tep size is invalid. */
#define FM_ERR_TUNNEL_TEP_SIZE                    269

/** The specified tunnel group or rule is invalid. */
#define FM_ERR_TUNNEL_INVALID_ENTRY               270

/** The specified mirror profile identifier is invalid. */
#define FM_ERR_INVALID_MIRROR_PROFILE             271

/** The specified profile index is invalid. */
#define FM_ERR_INVALID_PROFILE_INDEX              272

/** The specified tunnel has not yet been configured and cannot be used. */
#define FM_ERR_TUNNEL_NOT_CONFIGURED              273

/** Attribute is read-only. */
#define FM_ERR_READONLY_ATTRIB                    274

/** Invalid PCI Express Endpoint configuration */
#define FM_ERR_INVALID_PEP_MODE                   275

/** The Virtual Network Tunnel has not been configured. */
#define FM_ERR_VN_TUNNEL_NOT_CONFIGURED           276

/** The Mirror Group must specify an encap vlan to work. */
#define FM_ERR_MIRROR_NO_VLAN_ENCAP               277

/** This request is not supported in Transparent mode. */
#define FM_ERR_INVALID_IN_VN_TRANSPARENT_MODE     278

/** Virtual Network is in use. */
#define FM_ERR_VIRTUAL_NETWORK_IN_USE             279

/** Pep port is not scheduled. */
#define FM_ERR_PEP_PORT_NOT_SCHEDULED             280

/** Port is not a member of the vlan. */
#define FM_ERR_PORT_NOT_VLAN_MEMBER               281

/** Request only valid with a virtual router. */
#define FM_ERR_VIRTUAL_ROUTER_ONLY                282


/** @} (end of Doxygen group) */


/* returns error string for given error */
const char *fmErrorMsg(fm_int err);

/* returns status code given a string containing the status code name */
fm_status fmErrorCode(const char *errString);

#endif /* __FM_FM_ERRNO_H */
